import React from 'react';
import type { ProjectIdea } from '../../types/project';
import type { StudentProfile } from '../../types/profile';
import { Modal } from '../common/Modal';
import { Printer, Download } from 'lucide-react';

interface PrintableProjectBriefProps {
  isOpen: boolean;
  onClose: () => void;
  project: ProjectIdea;
  profile: StudentProfile;
}

export const PrintableProjectBrief: React.FC<PrintableProjectBriefProps> = ({
  isOpen,
  onClose,
  project,
  profile,
}) => {
  const handlePrint = () => {
    window.print();
  };

  const handleDownloadMarkdown = () => {
    const markdownContent = `# CAPSTONE PROJECT SPECIFICATION BRIEF
**Project Title:** ${project.title}
**Domain:** ${project.domain}
**Student / Branch:** ${profile.degreeBranch}
**Duration:** ${project.estimatedDuration} (${profile.weeklyHours} hrs/week commitment, Team Size: ${profile.teamSize})
**Feasibility Score:** ${project.feasibilityScore}/10 | **Innovation Score:** ${project.innovationScore}/10

---

## 1. EXECUTIVE SUMMARY & VALUE PROPOSITION
${project.valueProposition}

### Problem Statement
${project.problemStatement}

### Proposed Solution
${project.proposedSolution}

### Unique Differentiator
${project.uniqueDifferentiator}

---

## 2. TARGET USERS & STAKEHOLDERS
${project.targetUsers.map((u) => `- ${u}`).join('\n')}

---

## 3. FEATURE SCOPE ARCHITECTURE

### Phase 1: MVP Core Features (Deliverable)
${project.mvpFeatures.map((f) => `- **${f.title}:** ${f.description}`).join('\n')}

### Phase 2: Future Expansion (Thesis Scope)
${project.futureScope.map((f) => `- **${f.title}:** ${f.description}`).join('\n')}

---

## 4. RECOMMENDED TECHNOLOGY STACK & RATIONALE
${project.recommendedStack.map((s) => `- **${s.category}:** ${s.technology}\n  *Rationale:* ${s.reason}`).join('\n')}

### System Architecture Summary
${project.architectureSummary}

### Data & Infrastructure
- **Primary Data/API:** ${project.dataHardwareRequirements.primaryDataOrAPI}
- **Mock Data Fallback:** ${project.dataHardwareRequirements.mockAlternative}
- **Hardware Notes:** ${project.dataHardwareRequirements.hardwareNotes}

---

## 5. WEEK-BY-WEEK MILESTONE ROADMAP
${project.milestones
  .map(
    (m) => `### Week ${m.week}: ${m.phaseTitle}
- **Deliverable:** ${m.deliverable}
- **Tasks:**
${m.tasks.map((t) => `  * ${t}`).join('\n')}`
  )
  .join('\n\n')}

---

## 6. RISK ASSESSMENT & MITIGATION
${project.risks.map((r) => `- **Risk [${r.impact} Impact]:** ${r.risk}\n  *Mitigation:* ${r.mitigation}`).join('\n')}

---
*Generated by ProjectPilot AI • Academic Technology System*
`;

    const blob = new Blob([markdownContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project.title.toLowerCase().replace(/[^a-z0-9]/g, '_')}_brief.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Executive Capstone Project Brief (Print / Export)">
      <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.75rem', marginBottom: '1.25rem' }}>
        <button onClick={handleDownloadMarkdown} className="btn btn-secondary btn-sm">
          <Download size={14} /> Download Markdown (.md)
        </button>
        <button onClick={handlePrint} className="btn btn-primary btn-sm">
          <Printer size={14} /> Print / Save as PDF
        </button>
      </div>

      <div
        id="printable-brief-area"
        style={{
          backgroundColor: '#FFFFFF',
          border: '1px solid #CBD5E1',
          borderRadius: '8px',
          padding: '2.5rem',
          color: '#0F172A',
          fontFamily: 'serif, sans-serif',
          lineHeight: 1.6,
          maxHeight: '65vh',
          overflowY: 'auto',
        }}
      >
        <div style={{ borderBottom: '2px solid #0F172A', paddingBottom: '1rem', marginBottom: '1.5rem' }}>
          <div style={{ fontSize: '0.75rem', fontWeight: 700, textTransform: 'uppercase', color: '#4F46E5' }}>
            Academic Capstone Brief • ProjectPilot AI Specification
          </div>
          <h1 style={{ fontSize: '1.6rem', fontWeight: 800, margin: '0.3rem 0' }}>{project.title}</h1>
          <div style={{ fontSize: '0.85rem', color: '#475569' }}>
            <strong>Degree Program:</strong> {profile.degreeBranch} | <strong>Domain:</strong> {project.domain} | <strong>Timeline:</strong> {project.estimatedDuration} ({profile.weeklyHours}h/wk)
          </div>
          <div style={{ fontSize: '0.85rem', color: '#0D9488', fontWeight: 700, marginTop: '0.3rem' }}>
            Feasibility Score: {project.feasibilityScore}/10 | Innovation Rating: {project.innovationScore}/10
          </div>
        </div>

        <section style={{ marginBottom: '1.5rem' }}>
          <h3 style={{ fontSize: '1.1rem', fontWeight: 700, borderBottom: '1px solid #E2E8F0', paddingBottom: '0.3rem', marginBottom: '0.5rem' }}>
            1. Executive Summary & Value Proposition
          </h3>
          <p style={{ fontStyle: 'italic', marginBottom: '0.75rem' }}>{project.valueProposition}</p>
          <p style={{ fontSize: '0.9rem', marginBottom: '0.5rem' }}><strong>Problem:</strong> {project.problemStatement}</p>
          <p style={{ fontSize: '0.9rem', marginBottom: '0.5rem' }}><strong>Solution:</strong> {project.proposedSolution}</p>
          <p style={{ fontSize: '0.9rem' }}><strong>Unique Differentiator:</strong> {project.uniqueDifferentiator}</p>
        </section>

        <section style={{ marginBottom: '1.5rem' }}>
          <h3 style={{ fontSize: '1.1rem', fontWeight: 700, borderBottom: '1px solid #E2E8F0', paddingBottom: '0.3rem', marginBottom: '0.5rem' }}>
            2. Target Users
          </h3>
          <ul style={{ paddingLeft: '1.25rem', fontSize: '0.9rem' }}>
            {project.targetUsers.map((u, i) => (
              <li key={i}>{u}</li>
            ))}
          </ul>
        </section>

        <section style={{ marginBottom: '1.5rem' }}>
          <h3 style={{ fontSize: '1.1rem', fontWeight: 700, borderBottom: '1px solid #E2E8F0', paddingBottom: '0.3rem', marginBottom: '0.5rem' }}>
            3. Feature Scope
          </h3>
          <h4 style={{ fontSize: '0.95rem', fontWeight: 700, color: '#4F46E5', margin: '0.4rem 0' }}>Phase 1: MVP Core Deliverable</h4>
          <ul style={{ paddingLeft: '1.25rem', fontSize: '0.875rem' }}>
            {project.mvpFeatures.map((f) => (
              <li key={f.id}><strong>{f.title}:</strong> {f.description}</li>
            ))}
          </ul>
        </section>

        <section style={{ marginBottom: '1.5rem' }}>
          <h3 style={{ fontSize: '1.1rem', fontWeight: 700, borderBottom: '1px solid #E2E8F0', paddingBottom: '0.3rem', marginBottom: '0.5rem' }}>
            4. Technology Architecture & Stack Rationale
          </h3>
          <ul style={{ paddingLeft: '1.25rem', fontSize: '0.875rem', marginBottom: '0.75rem' }}>
            {project.recommendedStack.map((s, i) => (
              <li key={i}><strong>{s.category}:</strong> {s.technology} — <em>{s.reason}</em></li>
            ))}
          </ul>
          <p style={{ fontSize: '0.875rem' }}><strong>System Architecture:</strong> {project.architectureSummary}</p>
        </section>

        <section>
          <h3 style={{ fontSize: '1.1rem', fontWeight: 700, borderBottom: '1px solid #E2E8F0', paddingBottom: '0.3rem', marginBottom: '0.5rem' }}>
            5. Risk Management Strategy
          </h3>
          <ul style={{ paddingLeft: '1.25rem', fontSize: '0.875rem' }}>
            {project.risks.map((r, i) => (
              <li key={i}><strong>Risk ({r.impact}):</strong> {r.risk} — <em>Mitigation: {r.mitigation}</em></li>
            ))}
          </ul>
        </section>
      </div>
    </Modal>
  );
};
